//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 game.rc 使用
//
#define IDD_ABOUTBOX                    100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_MAINFRAME                   128
#define IDR_GAMETYPE                    129
#define IDB_RACKET                      131
#define IDB_ERASER1                     131
#define IDB_BITMAP1                     132
#define IDB_BACKGROUND                  132
#define IDB_CORNER                      133
#define IDB_BALL1                       134
#define IDB_BALL2                       135
#define IDB_BALL3                       136
#define IDB_BALL4                       137
#define IDB_0                           138
#define IDB_2                           140
#define IDB_3                           141
#define IDB_4                           142
#define IDB_5                           143
#define IDB_6                           144
#define IDB_7                           145
#define IDB_8                           146
#define IDB_9                           147
#define IDB_CENTER                      149
#define IDB_ERASER2                     150
#define IDB_ERASER3                     151
#define IDB_CONTINUE                    152
#define IDC_GAMECURSOR                  153
#define IDB_HELP                        155
#define IDB_BITMAP2                     156
#define IDB_LOADING                     156
#define IDB_BOMB1                       157
#define IDB_BOMB2                       158
#define IDB_BOMB3                       159
#define IDB_BITMAP3                     160
#define IDB_BOMB4                       160
#define IDB_PNG1                        164
#define IDB_PD1                         171
#define IDB_PD2                         172
#define IDB_PD3                         173
#define IDB_PD4                         174
#define IDB_PL1                         175
#define IDB_PL2                         176
#define IDB_PL3                         177
#define IDB_PL4                         178
#define IDB_PR1                         179
#define IDB_PR2                         180
#define IDB_PR3                         181
#define IDB_PR4                         182
#define IDB_PU1                         183
#define IDB_PU2                         184
#define IDB_PU3                         185
#define IDB_BITMAP19                    186
#define IDB_PU4                         186
#define IDB_GREENS                      187
#define IDB_ENEMY1                      201
#define IDB_ENEMY2                      202
#define IDB_ENEMY3                      203
#define IDB_ENEMY4                      204
#define IDB_ENEMY5                      205
#define IDB_ENEMY6                      206
#define IDB_ENEMY7                      207
#define IDB_ENEMY8                      208
#define IDB_ENEMY9                      209
#define IDB_PNG2                        210
#define IDB_FIRE2                       211
#define IDB_FIRE3                       212
#define IDB_FIRE4                       213
#define IDB_FIRE1                       216
#define IDB_MINUS                       217
#define IDB_WALL                        218
#define IDB_FIRED1                      220
#define IDB_FIRED2                      221
#define IDB_FIRED3                      222
#define IDB_FIRED4                      223
#define IDB_FIREL1                      224
#define IDB_FIREL2                      225
#define IDB_FIREL3                      226
#define IDB_FIREL4                      227
#define IDB_FIRELR1                     228
#define IDB_FIRELR2                     229
#define IDB_FIRELR3                     230
#define IDB_FIRELR4                     231
#define IDB_FIRER1                      232
#define IDB_FIRER2                      233
#define IDB_FIRER3                      234
#define IDB_FIRER4                      235
#define IDB_FIREU1                      236
#define IDB_FIREU2                      237
#define IDB_FIREU3                      238
#define IDB_FIREU4                      239
#define IDB_FIREUD1                     240
#define IDB_FIREUD2                     241
#define IDB_FIREUD3                     242
#define IDB_FIREUD4                     243
#define IDB_ESWALL                      244
#define IDB_ESWALL1                     245
#define IDB_ESWALL5                     246
#define IDB_ESWALL4                     247
#define IDB_ESWALL3                     248
#define IDB_ESWALL2                     249
#define IDB_WALL1                       251
#define IDB_DOOR                        252
#define IDB_TITLE                       253
#define IDB_START                       257
#define IDB_1                           259
#define IDB_LEFT                        260
#define IDB_TIME                        261
#define IDB_BITMAP4                     262
#define IDB_BOMBNUM                     262
#define IDB_SPEED                       263
#define IDB_BOMBPOW                     264
#define IDB_CONTROL                     265
#define IDB_CROSSBOMB                   266
#define IDB_CROSSWALL                   267
#define IDB_MISSALL                     268
#define IDB_MISSFIRE                    269
#define IDB_LEVEL1                      270
#define IDB_LEVEL2                      271
#define IDB_LEVEL3                      272
#define IDB_LEVEL4                      273
#define IDB_LEVEL5                      274
#define IDB_LEVEL6                      275
#define IDB_LEVEL7                      276
#define IDB_LEVEL8                      277
#define IDB_LEVEL9                      278
#define IDB_LEVEL10                     279
#define IDB_LEVEL11                     280
#define IDB_LEVEL12                     281
#define IDB_BALL                        282
#define IDB_PLAYERDEAD1                 285
#define IDB_PLAYERDEAD2                 286
#define IDB_PLAYERDEAD3                 287
#define IDB_PLAYERDEAD4                 288
#define IDB_PLAYERDEAD5                 289
#define IDB_PLAYERDEAD6                 290
#define IDB_PLAYERDEAD7                 291
#define IDB_GAMEOVER                    292
#define IDB_GAMEPASS                    293
#define IDB_MOUSE                       294
#define IDB_ABOUT                       295
#define IDB_TOP                         296
#define IDB_ABOUTUS                     298
#define IDB_HOWTOPLAY                   299
#define IDB_ENEMY11                     300
#define IDB_ENEMY12                     301
#define IDB_ENEMY13                     302
#define IDB_ENEMY14                     303
#define IDB_ENEMY15                     304
#define IDB_ENEMY16                     305
#define IDB_ENEMY17                     306
#define IDB_ENEMY18                     307
#define IDB_ENEMY19                     308
#define IDB_ENEMY21                     309
#define IDB_ENEMY22                     310
#define IDB_ENEMY23                     311
#define IDB_ENEMY24                     312
#define IDB_ENEMY25                     313
#define IDB_ENEMY26                     314
#define IDB_ENEMY27                     315
#define IDB_ENEMY28                     316
#define IDB_ENEMY29                     317
#define IDB_ENEMY31                     318
#define IDB_ENEMY32                     319
#define IDB_ENEMY33                     320
#define IDB_ENEMY34                     321
#define IDB_ENEMY35                     322
#define IDB_ENEMY36                     323
#define IDB_ENEMY37                     324
#define IDB_ENEMY38                     325
#define IDB_ENEMY39                     326
#define IDC_README                      1001
#define ID_FILE_PAUSE                   32771
#define ID_TOGGLE_FULLSCREEN            32772
#define ID_BUTTON_FULLSCREEN            32773
#define ID_BUTTON_PAUSE                 32774
#define ID_BUTTON_UNITTEST              32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        327
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
